name: Continuous Integration - Framework Benchmarking

on:
  pull_request:
    branches:
      - main

jobs:
  coordinate-runners:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework-runner: [SeleniumRunner, PlaywrightRunner]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Speeds up subsequent runs by caching dependencies

  #1. Start the local server by jumping into the bookstore-app directory
      - name: Start Local Web Server
        run: |
          cd bookstore-app
          python3 -m http.server 5500 &
          sleep 3

      # Runs Selenium Isolated Suite
      - name: Execute Isolated Selenium Testing Suite
        run: mvn clean test -Dtest=com.thesis.automation.selenium.runners.SeleniumRunner

      # Runs Playwright Isolated Suite
      - name: Execute Isolated Playwright Testing Suite
        run: mvn clean test -Dtest=com.thesis.automation.playwright.runners.PlaywrightRunner

      