name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'automation-framework/**'

  pull_request:
    branches:
      - main
    paths:
      - 'automation-framework/**' # 💡 Tests ONLY trigger if changes occur inside this folder

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Subfolder to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./bookstore-app # Tells the runner to ONLY grab files inside bookstore-app folder
          branch: gh-pages # It pushes them to a clean, separate branch for hosting